import type { Metadata } from "next";
import "../app/global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="bg-black px-4 py-4">
          <p className="text-white text-3xl">Header</p>
        </header>
        {children}
        <footer className="bg-black px-4 py-4">
          <p className="text-white text-lg">Footer</p>
        </footer>
      </body>
    </html>
  );
}
